name: 'Hydra CI Build'
description: 'Wait for a Hydra build and get build products'
author: 'Rodney Lorrimar <rodney.lorrimar@iohk.io>'
inputs:
  hydra:
    description: 'URL of Hydra instance'
    required: true
    default: 'https://hydra.iohk.io/'
  jobs:
    description: 'Space-separated list of job names to get URLs for'
    required: false
    default: ''
  evaluation:
    description: 'Previously completed Hydra evaluation as JSON'
    required: false
    default: ''
  builds:
    description: 'Previously found Hydra builds as JSON'
    required: false
    default: ''

outputs:
  evalURL:
    description: 'Link to evaluation page on Hydra'
  buildURLs:
    description: 'Space-separated list of build URLs corresponding to jobs'
  buildProducts:
    description: 'Space-separated list of build product download URLs from the builds'

  evaluation:
    description: 'Hydra evaluation as JSON'
  builds:
    description: 'Hydra builds as JSON'
  timings:
    description: 'JSON object with build time observations'

runs:
  using: 'node12'
  main: 'dist/index.js'
