name: 'Hydra CI Build'
description: 'Wait for a Hydra build and get build products'
author: 'Rodney Lorrimar <rodney.lorrimar@iohk.io>'
inputs:
  hydra:
    description: 'URL of Hydra instance'
    required: true
    default: 'https://hydra.iohk.io/'
  jobs:
    description: 'Space-separated list of job names to get'
    required: false
    default: ''

outputs:
  eval:
    description: 'URL of eval'
  builds:
    description: 'Space-separated list of build URLs corresponding to jobs'
  buildProducts:
    description: 'Space-separated list of build product download URLs from the builds'
  timings:
    description: 'JSON object with build time observations'

runs:
  using: 'node12'
  main: 'dist/index.js'
