name: 'Hydra CI Build'
description: 'Wait for a Hydra build and get build products'
author: 'Rodney Lorrimar <rodney.lorrimar@iohk.io>'
inputs:
  hydra:
    description: 'URL of Hydra instance'
    required: true
    default: 'https://hydra.iohk.io/'
  statusName:
    description: 'The GitHub CI status posted by Hydra when evaluation finishes.'
    required: true
    default: 'ci/hydra-eval'
  jobs:
    description: 'Space-separated list of job names to get URLs for'
    required: false
    default: ''
  requiredJob:
    description: 'Name of the job which is required for the build to succeed. Optional - only used for status badge.'
    required: false
    default: ''
  project:
    description: 'Name of the Hydra project. Optional - only used for status badge.'
    required: false
    default: ''
  jobset:
    description: 'Name of the jobset. Optional - only used for status badge.'
    required: false
    default: ''
  evaluation:
    description: 'Previously completed Hydra evaluation as JSON'
    required: false
    default: ''
  builds:
    description: 'Previously found Hydra builds as JSON'
    required: false
    default: ''
  badge:
    description: |-
      Set to non-empty to create CI status badge. This takes longer
      because it needs to query every build in the evaluation.
    required: false
    default: ''

outputs:
  evalURL:
    description: 'Link to evaluation page on Hydra'
  buildURLs:
    description: 'Space-separated list of build URLs corresponding to jobs'
  buildProducts:
    description: 'Space-separated list of build product download URLs from the builds'

  evaluation:
    description: 'Hydra evaluation as JSON'
  builds:
    description: 'Hydra builds as JSON'
  timings:
    description: 'JSON object with build time observations'
  badge:
    description: |-
      URL of a shields.io badge for the build, if the `badge`,
      `project`, and `jobset` inputs were set.

runs:
  using: 'node12'
  main: 'dist/index.js'
