name: build-test

on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
    tags:
      - 'v*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dependencies
        run: |
          npm install
      - name: Build
        run: |
          npm run build
      - name: Package
        run: |
          npm run package
      - name: Update
        run: |
          git config --global user.name 'GitHub Actions
          git config --global user.email 'rvl@users.noreply.github.com'
          if git commit -am "Rebuild dist/index.js"; then
            git push
          fi
